#!/usr/bin/env bash

DOTFILES=$HOME/dotfiles
STOW_FOLDER=(nvim tmux powerlevel10k zsh)

pushd $DOTFILES
for folder in ${STOW_FOLDER[@]}
do
    echo "stow $folder"
    stow -D $folder
    stow $folder
done
popd
